services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=swift_codes_db
      - PORT=8080
      - SWIFT_CODES_FILE_PATH=./data/Interns_2025_SWIFT_CODES.xlsx
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: